In [1]:
print ("hello")

hello


In [1]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[:,:,np.newaxis, np.newaxis] == B)

print (A)
print (B)
print (A[:,:,np.newaxis])
print ('-'*50)
print (A[:,:,np.newaxis, np.newaxis])
print (np.where(C))
print ("result"+'-'*50)
print (np.where(C.any((3,1)).all(1)))
print ('-'*50)
print (np.where(C.any((1))))
print ('-'*50)
print (np.where(C.any((1)).all(1)))

[[2 0 0]
 [3 4 3]
 [3 3 4]
 [4 4 4]
 [3 0 2]
 [1 2 2]
 [0 2 1]
 [4 3 4]]
[[3 1]
 [1 2]]
[[[2]
  [0]
  [0]]

 [[3]
  [4]
  [3]]

 [[3]
  [3]
  [4]]

 [[4]
  [4]
  [4]]

 [[3]
  [0]
  [2]]

 [[1]
  [2]
  [2]]

 [[0]
  [2]
  [1]]

 [[4]
  [3]
  [4]]]
--------------------------------------------------
[[[[2]]

  [[0]]

  [[0]]]


 [[[3]]

  [[4]]

  [[3]]]


 [[[3]]

  [[3]]

  [[4]]]


 [[[4]]

  [[4]]

  [[4]]]


 [[[3]]

  [[0]]

  [[2]]]


 [[[1]]

  [[2]]

  [[2]]]


 [[[0]]

  [[2]]

  [[1]]]


 [[[4]]

  [[3]]

  [[4]]]]
(array([0, 1, 1, 2, 2, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7], dtype=int64), array([0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 2, 1, 2, 2, 1], dtype=int64), array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0], dtype=int64), array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0], dtype=int64))
result--------------------------------------------------
(array([4, 5, 6], dtype=int64),)
--------------------------------------------------
(array([0, 1, 2, 4, 4, 5, 5, 5, 6, 6, 6, 7], dtype=int64), a

In [1]:
import numpy as np

a = np.array([10,7,2,0])
b = np.array([10,9,8,7,6,5,4,3,2,1])
print (a == b)
print ('-'*50)
c = a [...,np.newaxis] == b
print (c)
print ('c location'+'-'*50)
print (np.where(c))
print ('Axis 1 combine'+'-'*50)
print (np.where(c.any(1)))
print ('-'*50)
print (np.where(c.any(0)))
print ('-'*50)
print (np.where(c.any((1,0))))

False
--------------------------------------------------
[[ True False False False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False False]]
c location--------------------------------------------------
(array([0, 1, 2], dtype=int64), array([0, 3, 8], dtype=int64))
Axis 1 combine--------------------------------------------------
(array([0, 1, 2], dtype=int64),)
--------------------------------------------------
(array([0, 3, 8], dtype=int64),)
--------------------------------------------------
(array([0], dtype=int64),)


<ipython-input-1-866d05e116cc>:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print (a == b)


In [5]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[:,:,np.newaxis, np.newaxis] == B)
print (A)
print (B)

rows = np.where(C.any((3,1)).all(1))[0]
print ('-'*50)
print (np.where(C))
print ('-'*50)
print (np.where(C.any((3))))
print ('-'*50)
print (np.where(C.any((2))))
print ('-'*50)
print (np.where(C.any((1))))
print ('-'*50)
print (np.where(C.any((3,1))))
print ('-'*50)
print (np.where(C.any((3,1)).all(0)))
print ('-'*50)
print (rows)

[[2 0 4]
 [0 3 2]
 [1 2 0]
 [0 2 4]
 [1 4 1]
 [0 0 1]
 [3 0 4]
 [4 3 4]]
[[3 0]
 [4 0]]
--------------------------------------------------
(array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7,
       7], dtype=int64), array([1, 1, 2, 0, 0, 1, 2, 2, 0, 0, 2, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1,
       2], dtype=int64), array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1], dtype=int64), array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0], dtype=int64))
--------------------------------------------------
(array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7,
       7], dtype=int64), array([1, 1, 2, 0, 0, 1, 2, 2, 0, 0, 2, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1,
       2], dtype=int64), array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1], dtype=int64))
--------------------------------------------------
(array([0, 0, 1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 6, 7, 7, 7], dtype=int64), 

In [5]:
import numpy as np

A = np.array([10,7,2,0])
B = np.array([10,9,8,7,6,5,4,3,2,1])
print (A == B)
print ('-'*50)
C = A [...,np.newaxis] == B
print (C)
print ('C location'+'-'*50)
print (np.where(C))
print ('Axis 1 combine'+'-'*50)
print (np.where(C.any(1)))
print ('-'*50)
D = A [np.where(C.any(1))[0]]
print (D.sum(0))

False
--------------------------------------------------
[[ True False False False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False False]]
C location--------------------------------------------------
(array([0, 1, 2], dtype=int64), array([0, 3, 8], dtype=int64))
Axis 1 combine--------------------------------------------------
(array([0, 1, 2], dtype=int64),)
--------------------------------------------------
19


<ipython-input-5-c562bec63b74>:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print (A == B)


In [17]:
import numpy as np # 创建一个二维数组
A = np.arange(1,11).reshape(2,5)
print (A,"\n")
sum0 = A.sum(0)
sum1 = A.sum(1)
print("0轴折叠\n",sum0)
print("1轴折叠\n",sum1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

0轴折叠
 [ 7  9 11 13 15]
1轴折叠
 [15 40]
